name: Alerts
main: darkness\Alerts\Alerts
author: darknesspl
version: 1.0
api: 5.0.0

commands:
  alert:
   description: Command alert
   permission: darknesspl.alerts.command

permissions:
 darknesspl.alerts.command:
    description: Permission for alert command 
    default: op
